#!/usr/bin/env node

/**
 * Webpage Technology & NPM Package Scanner (Dynamic Zero-List Engine)
 * 
 * Discovers NPM packages, frameworks, and UI components dynamically without
 * maintaining hardcoded lists of thousands of packages:
 * 
 * 1. Source Map Mining: Dissects .map files to extract exact node_modules/@scope/pkg paths
 * 2. Bundler License Mining: Probes companion .LICENSE.txt files generated by Webpack/Vite/esbuild
 * 3. Banner License Mining: Extracts preserved license headers (e.g. @license pkg)
 * 4. Runtime & Architecture Probing: Next.js, Nuxt, Astro, Remix, Vite, Tailwind, Radix
 */

const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const https = require('node:https');
const { URL } = require('node:url');

const USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function showHelp() {
  console.log(`
Usage:
  node scan-webpage.js <url> [options]
  curl -sL <url> | node scan-webpage.js <url> --stdin

Arguments:
  <url>               The target webpage URL (e.g. https://example.com)

Options:
  --stdin             Read webpage HTML directly from standard input (useful with curl)
  --file, -f <path>   Read webpage HTML from a saved local file
  --output, -o <path> Path to save the JSON results (e.g. ./scan-results.json)
  --json              Print only raw JSON output to stdout
  --help, -h          Display this help message
`);
}

function fetchUrl(targetUrl, maxRedirects = 5) {
  return new Promise((resolve, reject) => {
    if (maxRedirects < 0) {
      return reject(new Error('Too many redirects'));
    }

    const parsed = new URL(targetUrl);
    const client = parsed.protocol === 'https:' ? https : http;

    const req = client.get(
      targetUrl,
      {
        headers: {
          'User-Agent': USER_AGENT,
          'Accept': 'text/html,application/xhtml+xml,application/xml,application/json,*/*;q=0.9',
          'Accept-Language': 'en-US,en;q=0.9'
        },
        timeout: 15000
      },
      (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          const redirectUrl = new URL(res.headers.location, targetUrl).toString();
          return resolve(fetchUrl(redirectUrl, maxRedirects - 1));
        }

        if (res.statusCode < 200 || res.statusCode >= 400) {
          return reject(new Error(`HTTP ${res.statusCode} ${res.statusMessage} for ${targetUrl}`));
        }

        const chunks = [];
        res.on('data', (chunk) => chunks.push(chunk));
        res.on('end', () => resolve({
          status: res.statusCode,
          headers: res.headers,
          data: Buffer.concat(chunks).toString('utf-8')
        }));
      }
    );

    req.on('error', reject);
    req.on('timeout', () => {
      req.destroy();
      reject(new Error(`Request timed out for ${targetUrl}`));
    });
  });
}

function extractScriptUrls(html, baseUrl) {
  const scriptUrls = [];
  const scriptRegex = /<script\b[^>]*?\bsrc=["']([^"']+)["'][^>]*>/gi;
  let match;
  while ((match = scriptRegex.exec(html)) !== null) {
    try {
      const fullUrl = new URL(match[1], baseUrl).toString();
      if (!scriptUrls.includes(fullUrl)) {
        scriptUrls.push(fullUrl);
      }
    } catch {
      // Ignore malformed URLs
    }
  }
  return scriptUrls;
}

/**
 * Dynamically extract NPM packages from Source Maps without any predefined package list
 */
function extractNodeModulesFromSourceMap(mapJson) {
  const packages = new Set();
  if (!mapJson || !Array.isArray(mapJson.sources)) {
    return [];
  }

  for (const src of mapJson.sources) {
    const match = src.match(/node_modules\/((?:@[a-zA-Z0-9_.-]+\/)?[a-zA-Z0-9_.-]+)/);
    if (match && match[1]) {
      const pkg = match[1];
      if (!pkg.startsWith('.')) {
        packages.add(pkg);
      }
    }
  }

  return Array.from(packages);
}

function isValidNpmPackageName(name) {
  if (!name || typeof name !== 'string') return false;
  const clean = name.trim();
  // Filter out 1-2 character minified variables (e.g. mr, tl, Ye)
  if (clean.length < 3 && !clean.startsWith('@')) return false;
  // Filter out JavaScript built-ins and keywords
  const jsKeywords = new Set(['string', 'number', 'boolean', 'void', 'function', 'object', 'undefined', 'null', 'true', 'false', 'symbol']);
  if (jsKeywords.has(clean.toLowerCase())) return false;
  // Filter out JavaScript member expressions (e.g. a.name, this.wa)
  if (clean.includes('.') && !clean.endsWith('.js')) return false;
  // Must match standard npm package naming convention
  return /^(?:@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/i.test(clean);
}

/**
 * Dynamically extract NPM packages from Webpack/Vite/esbuild .LICENSE.txt files
 */
function extractPackagesFromLicenseText(licenseText) {
  const packages = new Set();
  if (!licenseText) return [];

  const stopwords = new Set([
    'the', 'and', 'a', 'this', 'mit', 'apache', 'bsd', 'isc', 'gpl',
    'for', 'license', '@license', 'package', 'version', 'copyright', 'all', 'openjs', 'foundation', 'meta', 'platforms', 'inc'
  ]);

  // Match @license <name> or @license\n * <name>
  const licenseMatches = licenseText.matchAll(/@(?:license|preserve)(?:[ \t]*[\r\n]+[ \t]*\*?[ \t]*|[ \t]+)([@a-zA-Z0-9_.-]+)/gi);
  for (const match of licenseMatches) {
    const name = match[1];
    if (name && !stopwords.has(name.toLowerCase()) && isValidNpmPackageName(name)) {
      packages.add(name);
    }
  }

  // Match "Package: <name>" or "Name: <name>"
  const pkgMatches = licenseText.matchAll(/(?:package|name):\s*([@a-zA-Z0-9_.-]+)/gi);
  for (const match of pkgMatches) {
    const name = match[1];
    if (name && !stopwords.has(name.toLowerCase()) && isValidNpmPackageName(name)) {
      packages.add(name);
    }
  }

  // Match banner comments like "/*! <name> v<version>" or "/**\n * <name>"
  const bannerMatches = licenseText.matchAll(/(?:\/\*!|\/\*\*)[ \t]*[\r\n]*[ \t]*\*?[ \t]*([@a-zA-Z0-9_.-]+)(?:[ \t]+v?([0-9]+\.[0-9]+(?:\.[0-9]+)?))?/gi);
  for (const match of bannerMatches) {
    const name = match[1];
    if (name && !stopwords.has(name.toLowerCase()) && isValidNpmPackageName(name)) {
      packages.add(name);
    }
  }

  return Array.from(packages);
}

/**
 * Core dynamic scanning logic
 */
async function scanTarget(targetUrl, options = {}) {
  const startTime = Date.now();
  const detectedMap = new Map(); // pkgName -> { name, npmPackage, category, confidence, vectors: Set(), version }

  function recordPackage(pkgName, category, vector, confidence = 'high', version = null) {
    if (!pkgName || typeof pkgName !== 'string') return;
    const cleanName = pkgName.trim().replace(/['"]/g, '');
    if (!cleanName || cleanName.length < 2) return;

    if (!detectedMap.has(cleanName)) {
      detectedMap.set(cleanName, {
        name: cleanName,
        npmPackage: cleanName,
        category: category || 'NPM Package',
        confidence,
        vectors: new Set([vector]),
        version: version || null
      });
    } else {
      const existing = detectedMap.get(cleanName);
      existing.vectors.add(vector);
      if (confidence === 'high') existing.confidence = 'high';
      else if (confidence === 'medium' && existing.confidence === 'low') existing.confidence = 'medium';
      if (version && !existing.version) existing.version = version;
    }
  }

  // 1. Fetch HTML (or use pre-fetched HTML from curl/stdin/browser)
  let html = options.html || null;
  if (!html) {
    const fetched = await fetchUrl(targetUrl);
    html = fetched.data;
  }

  // 2. Structural Architecture & Meta-Framework Probing
  if (html.includes('__NEXT_DATA__') || html.includes('/_next/static/') || html.includes('id="__next"')) {
    recordPackage('next', 'Framework', 'Next.js hydration data (__NEXT_DATA__) & /_next/ routes', 'high');
    recordPackage('react', 'Core Library', 'Next.js React runtime dependency', 'high');
  }

  if (html.includes('__NUXT_DATA__') || html.includes('__NUXT__') || html.includes('/_nuxt/')) {
    recordPackage('nuxt', 'Framework', 'Nuxt hydration data (__NUXT_DATA__) & /_nuxt/ routes', 'high');
    recordPackage('vue', 'Core Library', 'Nuxt Vue runtime dependency', 'high');
  }

  if (html.includes('astro-island') || html.includes('/_astro/')) {
    recordPackage('astro', 'Framework', 'Astro island custom element (<astro-island>)', 'high');
  }

  if (html.includes('__remixContext')) {
    recordPackage('@remix-run/react', 'Framework', 'Remix runtime context (__remixContext)', 'high');
  }

  if (html.includes('ng-version') || html.includes('_ngcontent-')) {
    recordPackage('@angular/core', 'Framework', 'Angular root attribute (ng-version)', 'high');
  }

  if (html.includes('svelte-') || html.includes('__svelte')) {
    recordPackage('svelte', 'Framework', 'Svelte scoped class signature (svelte-*)', 'medium');
  }

  // 3. UI Component Systems & Styling Heuristics
  if (html.includes('data-radix-') || (html.includes('data-state=') && html.includes('data-orientation='))) {
    recordPackage('@radix-ui/react-primitive', 'UI Primitives', 'Radix UI DOM state attributes (data-radix-*, data-state)', 'high');
  }

  if (
    html.includes('flex items-center') ||
    html.includes('grid grid-cols-') ||
    html.includes('inline-flex items-center justify-center')
  ) {
    recordPackage('tailwindcss', 'CSS Framework', 'Tailwind CSS utility classes in DOM', 'high');
  }

  if (html.includes('MuiButton-root') || html.includes('MuiTypography-root') || html.includes('MuiBox-root')) {
    recordPackage('@mui/material', 'UI Library', 'Material UI class signatures (Mui*-root)', 'high');
  }

  if (html.includes('ant-btn') || html.includes('ant-layout') || html.includes('ant-modal')) {
    recordPackage('antd', 'UI Library', 'Ant Design class signatures (ant-*)', 'high');
  }

  if (html.includes('data-styled') || html.includes('sc-')) {
    recordPackage('styled-components', 'CSS-in-JS', 'Styled-components data attribute (data-styled)', 'medium');
  }

  if (html.includes('data-emotion') || html.includes('css-')) {
    recordPackage('@emotion/react', 'CSS-in-JS', 'Emotion style container (data-emotion)', 'medium');
  }

  // 4. Script URLs Inspection
  const scriptUrls = extractScriptUrls(html, targetUrl);

  // 5. Dynamic Source Map & License File Mining (Sample up to 8 same-origin scripts)
  const targetHost = new URL(targetUrl).host;
  const prioritizedScripts = scriptUrls
    .filter(u => {
      try { return new URL(u).host === targetHost; } catch { return false; }
    })
    .slice(0, 8);

  const discoveredFromSourceMaps = [];
  const discoveredFromLicenses = [];
  let sourceMapsFound = false;

  for (const scriptUrl of prioritizedScripts) {
    try {
      // 5A. Probe companion .LICENSE.txt file (generated by Webpack/Vite/esbuild)
      const licenseUrl = `${scriptUrl}.LICENSE.txt`;
      try {
        const licRes = await fetchUrl(licenseUrl);
        if (licRes.status === 200 && licRes.data) {
          const licPackages = extractPackagesFromLicenseText(licRes.data);
          for (const pkg of licPackages) {
            if (!discoveredFromLicenses.includes(pkg)) discoveredFromLicenses.push(pkg);
            recordPackage(pkg, 'NPM Dependency (License File)', `Discovered from companion license manifest (${path.basename(licenseUrl)})`, 'high');
          }
        }
      } catch {
        // License file probe non-blocking
      }

      // 5B. Fetch Script Content
      const scriptRes = await fetchUrl(scriptUrl);
      const code = scriptRes.data;

      // Extract inline banner comments from code
      const inlineLicPackages = extractPackagesFromLicenseText(code);
      for (const pkg of inlineLicPackages) {
        recordPackage(pkg, 'NPM Dependency (Banner)', `Discovered in script comment header (${path.basename(scriptUrl)})`, 'high');
      }

      // 5C. Probe Source Map
      let mapUrl = null;
      const sourceMapComment = code.match(/\/\/#\s*sourceMappingURL=([^\s]+)/);
      if (sourceMapComment && sourceMapComment[1]) {
        try {
          mapUrl = new URL(sourceMapComment[1], scriptUrl).toString();
        } catch {}
      } else {
        mapUrl = `${scriptUrl}.map`;
      }

      if (mapUrl) {
        try {
          const mapRes = await fetchUrl(mapUrl);
          if (mapRes.status === 200 && mapRes.data.startsWith('{')) {
            const mapJson = JSON.parse(mapRes.data);
            const pkgs = extractNodeModulesFromSourceMap(mapJson);
            if (pkgs.length > 0) {
              sourceMapsFound = true;
              for (const pkg of pkgs) {
                if (!discoveredFromSourceMaps.includes(pkg)) {
                  discoveredFromSourceMaps.push(pkg);
                }
                recordPackage(pkg, 'NPM Dependency (Source Map)', `Extracted directly from source map sources (${path.basename(scriptUrl)}.map)`, 'high');
              }
            }
          }
        } catch {
          // Source map probe non-blocking
        }
      }
    } catch {
      // Script fetch non-blocking
    }
  }

  const durationMs = Date.now() - startTime;
  const packagesList = Array.from(detectedMap.values()).map(item => ({
    ...item,
    vectors: Array.from(item.vectors)
  }));

  return {
    targetUrl,
    scannedAt: new Date().toISOString(),
    durationMs,
    totalScriptsFound: scriptUrls.length,
    scriptsAnalyzed: prioritizedScripts.length,
    sourceMapsFound,
    sourceMapPackagesCount: discoveredFromSourceMaps.length,
    licensePackagesCount: discoveredFromLicenses.length,
    detectedPackages: packagesList
  };
}

async function readStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.setEncoding('utf-8');
    process.stdin.on('data', chunk => chunks.push(chunk));
    process.stdin.on('end', () => resolve(chunks.join('')));
    process.stdin.on('error', reject);
  });
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    showHelp();
    process.exit(0);
  }

  const targetUrl = args.find(a => !a.startsWith('-'));
  if (!targetUrl) {
    console.error('Error: Please provide a valid URL.');
    showHelp();
    process.exit(1);
  }

  const jsonOnly = args.includes('--json');
  const useStdin = args.includes('--stdin');
  const fileIndex = args.findIndex(a => a === '--file' || a === '-f');
  const filePath = fileIndex !== -1 && args[fileIndex + 1] ? args[fileIndex + 1] : null;

  const outputIndex = args.findIndex(a => a === '--output' || a === '-o');
  const outputPath = outputIndex !== -1 && args[outputIndex + 1] ? args[outputIndex + 1] : null;

  try {
    let prefetchedHtml = null;
    if (useStdin) {
      if (!jsonOnly) console.log(`📥 Reading HTML from stdin...`);
      prefetchedHtml = await readStdin();
    } else if (filePath) {
      if (!jsonOnly) console.log(`📂 Reading HTML from local file: ${filePath}...`);
      prefetchedHtml = fs.readFileSync(path.resolve(process.cwd(), filePath), 'utf-8');
    }

    if (!jsonOnly) {
      console.log(`\n🔍 Scanning webpage: ${targetUrl}...`);
    }

    const result = await scanTarget(targetUrl, { html: prefetchedHtml });

    if (outputPath) {
      const resolved = path.resolve(process.cwd(), outputPath);
      fs.mkdirSync(path.dirname(resolved), { recursive: true });
      fs.writeFileSync(resolved, JSON.stringify(result, null, 2), 'utf-8');
      if (!jsonOnly) {
        console.log(`💾 Saved scan report to ${resolved}`);
      }
    }

    if (jsonOnly) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log(`\n================ DYNAMIC SCAN SUMMARY ================`);
      console.log(`Target: ${result.targetUrl}`);
      console.log(`Scanned in: ${result.durationMs}ms`);
      console.log(`Source Maps Discovered: ${result.sourceMapsFound ? 'YES' : 'NO'}`);
      console.log(`Packages from Source Maps: ${result.sourceMapPackagesCount}`);
      console.log(`Packages from License Manifests: ${result.licensePackagesCount}`);
      console.log(`Total Technologies Discovered: ${result.detectedPackages.length}\n`);

      const categories = {};
      for (const item of result.detectedPackages) {
        categories[item.category] = categories[item.category] || [];
        categories[item.category].push(item);
      }

      for (const [category, items] of Object.entries(categories)) {
        console.log(`📦 ${category}:`);
        for (const it of items) {
          console.log(`   • ${it.npmPackage || it.name} [Confidence: ${it.confidence}]`);
          for (const v of it.vectors) {
            console.log(`       - ${v}`);
          }
        }
        console.log('');
      }
    }
  } catch (error) {
    console.error(`\n❌ Scan failed: ${error.message}`);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  scanTarget,
  extractScriptUrls,
  extractNodeModulesFromSourceMap,
  extractPackagesFromLicenseText
};
